server:
  port: 9811

spring:
  application:
    name: FIRST-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: localhost

management:
  endpoint:
    web:
      exposure:
        include: "*"